db: ../dashboard.db

gradescope:
  gs_login: 'zives@live.com'
  gs_pwd: 'npY6$XV$dC7u7y#'
  use_threads: false
  enabled: true
  show: true
  semesters:
  - Fall 2023

canvas:
  api_key: 25~DVxlAzRpzDqMutw2f2r3TIK9Sm8ZwDnbgFPreTga3fjQZ3OdLPJDtBJSmM1Jfrzm
  site: https://canvas.upenn.edu
  course_ids:
  - 1741973
  - 1739572
  enabled: true
  show: true
  active_only: true
  include:
  - students
  - assignments
  - summaries
  - submissions

rubric:
  1741973:
    spreadsheet: "/Users/zives/Google\ Drive/Shared drives/CIS 5450 2023 Fall/more-fields-1741973.xlsx"
    midterm1:
      substring: Midterm 1
      points: 15
      max_score: 75
      max_extra_credit: 4
      source: Gradescope
    midterm2:
      substring: Midterm 2
      points: 15
      max_score: 75
      max_extra_credit: 4
      source: Gradescope
    homeworks:
      substring: Homework
      points: 40
      source: Gradescope
    quizzes:
      substring: review
      max_score: 210
      max_extra_credit: 0
      points: 7
      source: Canvas
    proposal:
      substring: Project Proposal
      points: 1.82
      source: Gradescope
    project:
      substring: Final Project
      points: 18.18
      source: Gradescope
    ec:
      substring: Extra Credit
      max_score: 1
      points: 1
  1739572:
    exams:
      substring: Midterm
      points: 15
    homeworks:
      substring: Homework
      points: 40
    quizzes:
      substring: review
      points: 2
    proposal:
      substring: Project Proposal
      points: 2
    project:
      substring: Final Project
      points: 28
    ec:
      substring: Extra Credit
      points: 1

  color_codes:
    is_submitted:
      test: row['Status'] != 'Missing'
      color: 'lightgray'
    is_below_mean:
      test: row['Status'] < mean
      color: 'red'

  summary_view:
    fields:
      -  'Email'
      -  'Last Name'
      -  'First Name'
      -  'Total Score'
      -  'Max Score'
